DROP TRIGGER IF EXISTS prevent_settlement_snapshot_mutation ON settlement_snapshots;
DROP TRIGGER IF EXISTS prevent_intelligence_market_measure_mutation ON intelligence_market_measures;
DROP TRIGGER IF EXISTS prevent_intelligence_market_event_mutation ON intelligence_market_events;
DROP TRIGGER IF EXISTS prevent_institutional_flow_revision_mutation ON institutional_flow_observations;
DROP TRIGGER IF EXISTS prevent_fund_holding_revision_mutation ON fund_holding_revisions;
DROP TRIGGER IF EXISTS prevent_corporate_disclosure_revision_mutation ON corporate_disclosure_revisions;
DROP FUNCTION IF EXISTS prevent_intelligence_revision_mutation();
DROP TABLE IF EXISTS fund_holding_revisions;
DROP TABLE IF EXISTS settlement_snapshots;
DROP TABLE IF EXISTS institutional_flow_observations;
DROP TABLE IF EXISTS intelligence_market_measures;
DROP TABLE IF EXISTS intelligence_market_events;
DROP TABLE IF EXISTS corporate_disclosure_revisions;
DROP TABLE IF EXISTS intelligence_provider_capabilities;
DROP TABLE IF EXISTS intelligence_external_identity_mappings;
DROP TABLE IF EXISTS derivative_contracts;
DROP TABLE IF EXISTS intelligence_funds;
DROP TABLE IF EXISTS intelligence_companies;
DROP TABLE IF EXISTS intelligence_institutions;
