apiVersion: v1
kind: ServiceAccount
metadata:
  name: atlas-runtime
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: atlas-migration
automountServiceAccountToken: false
