import { getTableName } from 'drizzle-orm';
import { describe, expect, it } from 'vitest';

import {
  alertEvaluations,
  alertRevisions,
  alerts,
  alertStates,
  alertTriggers,
  dataProviders,
  dataQualityIssues,
  ingestionRuns,
  instruments,
  instrumentSymbolHistory,
  fundamentalMetricSnapshots,
  fundamentalRatioSnapshots,
  fundamentalStatementSnapshots,
  marketOverviewSnapshots,
  marketRankSnapshots,
  notificationDeliveries,
  notificationOutbox,
  notificationPreferences,
  notifications,
  portfolioCashBalances,
  portfolioImportJobs,
  portfolioImportRows,
  portfolioPerformanceSnapshots,
  portfolioPositions,
  portfolioPositionSnapshots,
  portfolioRiskExposures,
  portfolioRiskSnapshots,
  portfolios,
  portfolioTransactions,
  portfolioValuationSnapshots,
  patternDefinitions,
  patternInstances,
  priceBars,
  providerInstrumentMappings,
  presetScanRevisions,
  presetScans,
  savedScanRevisions,
  savedScans,
  savedScanTags,
  scanCategories,
  scanResults,
  scanRunBatches,
  scanRunEvents,
  scanRuns,
  sectors,
  sectorMarketSnapshots,
  watchlistItems,
  watchlistItemTags,
  watchlists,
  strategies,
  strategyRevisions,
  backtestRuns,
  backtestDataSnapshots,
  backtestSummaries,
  backtestOrders,
  backtestFills,
  backtestTrades,
  backtestSeriesChunks,
  researchExperiments,
  researchExperimentRuns,
  incidents,
  incidentTimelineEvents,
  authSessions,
  featureFlags,
  featureFlagVersions,
  operationalAuditEvents,
  passwordResetTokens,
  releaseRecords,
  securityRateLimitBuckets,
  securityUsers,
  accountDeletionRequests,
  backupStatusChecks,
  legalHolds,
  recoveryDrills,
  retentionJobRuns,
  storedArtifacts,
  providerConnections,
  providerIngestionRuns,
  providerDataRevisions,
  dataQualityFindings,
  dataCorrectionRequests,
  communicationTemplates,
  communicationDeliveryAttempts,
  communicationProviderEvents,
  legalDocuments,
  userDocumentConsents,
} from './index';

describe('initial database schema', () => {
  it('exports versioned legal documents and user consent history', () => {
    expect([legalDocuments, userDocumentConsents].map(getTableName)).toEqual([
      'legal_documents',
      'user_document_consents',
    ]);
  });

  it('exports the six recovery and retention tables', () => {
    expect(
      [
        backupStatusChecks,
        recoveryDrills,
        retentionJobRuns,
        legalHolds,
        storedArtifacts,
        accountDeletionRequests,
      ].map(getTableName),
    ).toEqual([
      'backup_status_checks',
      'recovery_drills',
      'retention_job_runs',
      'legal_holds',
      'stored_artifacts',
      'account_deletion_requests',
    ]);
  });

  it('contains only the eight TASK-007 tables', () => {
    expect(
      [
        sectors,
        instruments,
        instrumentSymbolHistory,
        dataProviders,
        providerInstrumentMappings,
        priceBars,
        dataQualityIssues,
        ingestionRuns,
      ].map(getTableName),
    ).toEqual([
      'sectors',
      'instruments',
      'instrument_symbol_history',
      'data_providers',
      'provider_instrument_mappings',
      'price_bars',
      'data_quality_issues',
      'ingestion_runs',
    ]);
  });

  it('exports the ten scanner runtime tables', () => {
    expect(
      [
        scanCategories,
        savedScans,
        savedScanRevisions,
        savedScanTags,
        presetScans,
        presetScanRevisions,
        scanRuns,
        scanRunBatches,
        scanResults,
        scanRunEvents,
      ].map(getTableName),
    ).toEqual([
      'scan_categories',
      'saved_scans',
      'saved_scan_revisions',
      'saved_scan_tags',
      'preset_scans',
      'preset_scan_revisions',
      'scan_runs',
      'scan_run_batches',
      'scan_results',
      'scan_run_events',
    ]);
  });

  it('exports the twelve alerts, watchlists and notifications tables', () => {
    expect(
      [
        watchlists,
        watchlistItems,
        watchlistItemTags,
        alerts,
        alertRevisions,
        alertEvaluations,
        alertStates,
        alertTriggers,
        notifications,
        notificationPreferences,
        notificationDeliveries,
        notificationOutbox,
      ].map(getTableName),
    ).toEqual([
      'watchlists',
      'watchlist_items',
      'watchlist_item_tags',
      'alerts',
      'alert_revisions',
      'alert_evaluations',
      'alert_states',
      'alert_triggers',
      'notifications',
      'notification_preferences',
      'notification_deliveries',
      'notification_outbox',
    ]);
  });

  it('exports the eleven portfolio, transaction, projection and risk tables', () => {
    expect(
      [
        portfolios,
        portfolioTransactions,
        portfolioPositions,
        portfolioCashBalances,
        portfolioValuationSnapshots,
        portfolioPositionSnapshots,
        portfolioPerformanceSnapshots,
        portfolioRiskSnapshots,
        portfolioRiskExposures,
        portfolioImportJobs,
        portfolioImportRows,
      ].map(getTableName),
    ).toEqual([
      'portfolios',
      'portfolio_transactions',
      'portfolio_positions',
      'portfolio_cash_balances',
      'portfolio_valuation_snapshots',
      'portfolio_position_snapshots',
      'portfolio_performance_snapshots',
      'portfolio_risk_snapshots',
      'portfolio_risk_exposures',
      'portfolio_import_jobs',
      'portfolio_import_rows',
    ]);
  });

  it('exports the eight market intelligence read-model tables', () => {
    expect(
      [
        marketOverviewSnapshots,
        sectorMarketSnapshots,
        marketRankSnapshots,
        fundamentalStatementSnapshots,
        fundamentalMetricSnapshots,
        fundamentalRatioSnapshots,
        patternDefinitions,
        patternInstances,
      ].map(getTableName),
    ).toEqual([
      'market_overview_snapshots',
      'sector_market_snapshots',
      'market_rank_snapshots',
      'fundamental_statement_snapshots',
      'fundamental_metric_snapshots',
      'fundamental_ratio_snapshots',
      'pattern_definitions',
      'pattern_instances',
    ]);
  });

  it('exports the eleven strategy, backtest and experiment tables', () => {
    expect(
      [
        strategies,
        strategyRevisions,
        backtestRuns,
        backtestDataSnapshots,
        backtestSummaries,
        backtestOrders,
        backtestFills,
        backtestTrades,
        backtestSeriesChunks,
        researchExperiments,
        researchExperimentRuns,
      ].map(getTableName),
    ).toEqual([
      'strategies',
      'strategy_revisions',
      'backtest_runs',
      'backtest_data_snapshots',
      'backtest_summaries',
      'backtest_orders',
      'backtest_fills',
      'backtest_trades',
      'backtest_series_chunks',
      'research_experiments',
      'research_experiment_runs',
    ]);
  });

  it('exports the DB-009 incident runtime tables', () => {
    expect([incidents, incidentTimelineEvents].map(getTableName)).toEqual([
      'incidents',
      'incident_timeline_events',
    ]);
  });

  it('exports the eight security authority and operational-control tables', () => {
    expect(
      [
        securityUsers,
        authSessions,
        passwordResetTokens,
        securityRateLimitBuckets,
        featureFlags,
        featureFlagVersions,
        operationalAuditEvents,
        releaseRecords,
      ].map(getTableName),
    ).toEqual([
      'security_users',
      'auth_sessions',
      'password_reset_tokens',
      'security_rate_limit_buckets',
      'feature_flags',
      'feature_flag_versions',
      'operational_audit_events',
      'release_records',
    ]);
  });

  it('exports the five DB-011 provider lineage and correction tables', () => {
    expect(
      [
        providerConnections,
        providerIngestionRuns,
        providerDataRevisions,
        dataQualityFindings,
        dataCorrectionRequests,
      ].map(getTableName),
    ).toEqual([
      'provider_connections',
      'provider_ingestion_runs',
      'provider_data_revisions',
      'data_quality_findings',
      'data_correction_requests',
    ]);
  });

  it('exports the DB-011 communication governance tables', () => {
    expect(
      [
        communicationTemplates,
        communicationDeliveryAttempts,
        communicationProviderEvents,
      ].map(getTableName),
    ).toEqual([
      'communication_templates',
      'communication_delivery_attempts',
      'communication_provider_events',
    ]);
  });
});
