import type { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { AppModule } from '../app.module';
import { configureApplication } from '../bootstrap/configure-application';
import { createOpenApiDocument } from './openapi';

describe('OpenAPI document', () => {
  let application: INestApplication;

  beforeAll(async () => {
    const moduleReference = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    application = moduleReference.createNestApplication();
    configureApplication(application);
    await application.init();
  });

  afterAll(async () => {
    await application.close();
  });

  it('contains health, scanner, saved scan and watchlist operations', () => {
    const document = createOpenApiDocument(application);

    expect(document.info.version).toBe('1.0');
    expect(document.paths['/health/live']?.get).toBeDefined();
    expect(document.paths['/health/ready']?.get).toBeDefined();
    expect(document.paths['/api/v1/indicators']?.get).toBeDefined();
    expect(document.paths['/api/v1/indicators/{code}']?.get).toBeDefined();
    expect(document.paths['/api/v1/scanner/runs']?.post).toBeDefined();
    expect(document.paths['/api/v1/scanner/runs/{runId}']?.get).toBeDefined();
    expect(
      document.paths['/api/v1/scanner/runs/{runId}/results']?.get,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/scanner/runs/{runId}/cancel']?.post,
    ).toBeDefined();
    expect(document.paths['/api/v1/saved-scans']?.get).toBeDefined();
    expect(document.paths['/api/v1/saved-scans']?.post).toBeDefined();
    expect(document.paths['/api/v1/saved-scans/{id}']?.get).toBeDefined();
    expect(document.paths['/api/v1/saved-scans/{id}']?.patch).toBeDefined();
    expect(document.paths['/api/v1/saved-scans/{id}']?.delete).toBeDefined();
    expect(
      document.paths['/api/v1/saved-scans/{id}/clone']?.post,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/saved-scans/{id}/restore']?.post,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/saved-scans/{id}/revisions']?.get,
    ).toBeDefined();
    expect(JSON.stringify(document.paths['/api/v1/saved-scans'])).not.toContain(
      'public',
    );
    expect(JSON.stringify(document.paths['/api/v1/saved-scans'])).not.toContain(
      'share',
    );
    expect(document.paths['/api/v1/preset-scan-categories']?.get).toBeDefined();
    expect(document.paths['/api/v1/preset-scans']?.get).toBeDefined();
    expect(document.paths['/api/v1/preset-scans/{code}']?.get).toBeDefined();
    expect(
      document.paths['/api/v1/preset-scans/{code}/runs']?.post,
    ).toBeDefined();
    expect(document.paths['/api/v1/watchlists']?.get).toBeDefined();
    expect(document.paths['/api/v1/watchlists']?.post).toBeDefined();
    expect(document.paths['/api/v1/watchlists/{id}']?.get).toBeDefined();
    expect(document.paths['/api/v1/watchlists/{id}']?.patch).toBeDefined();
    expect(document.paths['/api/v1/watchlists/{id}']?.delete).toBeDefined();
    expect(
      document.paths['/api/v1/watchlists/{id}/restore']?.post,
    ).toBeDefined();
    expect(document.paths['/api/v1/watchlists/{id}/items']?.post).toBeDefined();
    expect(
      document.paths['/api/v1/watchlists/{id}/items/{itemId}']?.patch,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/watchlists/{id}/items/{itemId}']?.delete,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/watchlists/{id}/reorder']?.post,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/watchlists/{id}/market-summary']?.get,
    ).toBeDefined();
    expect(document.paths['/api/v1/alerts']?.get).toBeDefined();
    expect(document.paths['/api/v1/alerts']?.post).toBeDefined();
    expect(document.paths['/api/v1/alerts/{id}']?.get).toBeDefined();
    expect(document.paths['/api/v1/alerts/{id}']?.patch).toBeDefined();
    expect(document.paths['/api/v1/alerts/{id}']?.delete).toBeDefined();
    expect(document.paths['/api/v1/alerts/{id}/pause']?.post).toBeDefined();
    expect(document.paths['/api/v1/alerts/{id}/resume']?.post).toBeDefined();
    expect(document.paths['/api/v1/alerts/{id}/revisions']?.get).toBeDefined();
    expect(
      document.paths['/api/v1/alerts/{id}/evaluations']?.get,
    ).toBeDefined();
    expect(document.paths['/api/v1/alerts/{id}/triggers']?.get).toBeDefined();
    expect(document.paths['/api/v1/alerts/{id}/test']?.post).toBeDefined();
    expect(document.paths['/api/v1/notifications']?.get).toBeDefined();
    expect(
      document.paths['/api/v1/notifications/unread-count']?.get,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/notifications/{id}/read']?.post,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/notifications/{id}/unread']?.post,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/notifications/mark-all-read']?.post,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/notification-preferences']?.get,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/notification-preferences']?.put,
    ).toBeDefined();
    expect(document.paths['/api/v1/portfolios']?.get).toBeDefined();
    expect(document.paths['/api/v1/portfolios']?.post).toBeDefined();
    expect(document.paths['/api/v1/portfolios/{id}']?.get).toBeDefined();
    expect(document.paths['/api/v1/portfolios/{id}']?.patch).toBeDefined();
    expect(document.paths['/api/v1/portfolios/{id}']?.delete).toBeDefined();
    expect(
      document.paths['/api/v1/portfolios/{id}/restore']?.post,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/portfolios/{id}/transactions']?.get,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/portfolios/{id}/transactions']?.post,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/portfolios/{id}/transactions/{transactionId}']
        ?.get,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/portfolios/{id}/transactions/{transactionId}']
        ?.patch,
    ).toBeUndefined();
    expect(
      document.paths[
        '/api/v1/portfolios/{id}/transactions/{transactionId}/post'
      ]?.post,
    ).toBeDefined();
    expect(
      document.paths[
        '/api/v1/portfolios/{id}/transactions/{transactionId}/reverse'
      ]?.post,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/portfolios/{id}/positions']?.get,
    ).toBeDefined();
    const positionParameters =
      document.paths['/api/v1/portfolios/{id}/positions']?.get?.parameters;
    expect(JSON.stringify(positionParameters)).toContain('cursor');
    expect(JSON.stringify(positionParameters)).toContain('sortField');
    expect(JSON.stringify(positionParameters)).toContain('sortDirection');
    expect(JSON.stringify(positionParameters)).toContain('symbol');
    expect(
      document.paths['/api/v1/portfolios/{id}/valuation']?.get,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/portfolios/{id}/valuation-history']?.get,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/portfolios/{id}/recalculate']?.post,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/portfolios/{id}/performance']?.get,
    ).toBeDefined();
    expect(document.paths['/api/v1/portfolios/{id}/risk']?.get).toBeDefined();
    expect(
      document.paths['/api/v1/portfolios/{portfolioId}/imports']?.post,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/portfolios/{portfolioId}/imports/{jobId}']?.get,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/portfolios/{portfolioId}/imports/{jobId}/rows']
        ?.get,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/portfolios/{portfolioId}/imports/{jobId}/commit']
        ?.post,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/portfolios/{portfolioId}/imports/{jobId}/cancel']
        ?.post,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/portfolios/{portfolioId}/exports/transactions']
        ?.get,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/portfolios/{portfolioId}/exports/positions']?.get,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/portfolios/{portfolioId}/exports/performance']
        ?.get,
    ).toBeDefined();
    expect(
      JSON.stringify(
        document.paths['/api/v1/portfolios/{portfolioId}/imports']?.post
          ?.parameters,
      ),
    ).toContain('Idempotency-Key');
    expect(
      document.paths['/api/v1/portfolios/{portfolioId}/imports']?.post
        ?.requestBody,
    ).toBeDefined();
    expect(
      JSON.stringify(
        document.paths['/api/v1/portfolios/{id}/transactions']?.post
          ?.parameters,
      ),
    ).toContain('Idempotency-Key');
    expect(document.paths['/api/v1/market/overview']?.get).toBeDefined();
    expect(document.paths['/api/v1/market/breadth']?.get).toBeDefined();
    expect(document.paths['/api/v1/market/sectors']?.get).toBeDefined();
    expect(document.paths['/api/v1/market/rankings/{type}']?.get).toBeDefined();
    const rankingParameters =
      document.paths['/api/v1/market/rankings/{type}']?.get?.parameters;
    expect(JSON.stringify(rankingParameters)).toContain('cursor');
    expect(JSON.stringify(rankingParameters)).toContain('limit');
    expect(JSON.stringify(rankingParameters)).toContain('breakoutCandidates');
    expect(
      JSON.stringify(document.components?.schemas?.MarketResponseMetaDto),
    ).toContain('generationId');
    expect(
      JSON.stringify(document.components?.schemas?.MarketResponseMetaDto),
    ).toContain('dataCutoffAt');
    expect(document.paths['/api/v1/symbols/{symbol}']?.get).toBeDefined();
    expect(document.paths['/api/v1/symbols/{symbol}/quote']?.get).toBeDefined();
    expect(document.paths['/api/v1/symbols/{symbol}/chart']?.get).toBeDefined();
    expect(
      document.paths['/api/v1/symbols/{symbol}/signals']?.get,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/symbols/{symbol}/corporate-actions']?.get,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/symbols/{symbol}/financials']?.get,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/symbols/{symbol}/ratios']?.get,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/symbols/{symbol}/financial-trends']?.get,
    ).toBeDefined();
    expect(document.paths['/api/v1/patterns/catalog']?.get).toBeDefined();
    expect(
      document.paths['/api/v1/symbols/{symbol}/patterns']?.get,
    ).toBeDefined();
    expect(document.paths['/api/v1/market/patterns']?.get).toBeDefined();
    expect(document.paths['/api/v1/strategies']?.get).toBeDefined();
    expect(document.paths['/api/v1/strategies']?.post).toBeDefined();
    expect(document.paths['/api/v1/strategies/{id}']?.get).toBeDefined();
    expect(document.paths['/api/v1/strategies/{id}']?.patch).toBeDefined();
    expect(document.paths['/api/v1/strategies/{id}']?.delete).toBeDefined();
    expect(
      document.paths['/api/v1/strategies/{id}/restore']?.post,
    ).toBeDefined();
    expect(document.paths['/api/v1/strategies/{id}/clone']?.post).toBeDefined();
    expect(
      document.paths['/api/v1/strategies/{id}/revisions']?.get,
    ).toBeDefined();
    expect(document.paths['/api/v1/strategies/validate']?.post).toBeDefined();
    expect(document.paths['/api/v1/backtests']?.post).toBeDefined();
    expect(document.paths['/api/v1/backtests']?.get).toBeDefined();
    expect(document.paths['/api/v1/backtests/{id}']?.get).toBeDefined();
    expect(document.paths['/api/v1/backtests/{id}/cancel']?.post).toBeDefined();
    expect(document.paths['/api/v1/backtests/{id}/summary']?.get).toBeDefined();
    expect(document.paths['/api/v1/backtests/{id}/series']?.get).toBeDefined();
    expect(document.paths['/api/v1/backtests/{id}/trades']?.get).toBeDefined();
    expect(document.paths['/api/v1/backtests/{id}/orders']?.get).toBeDefined();
    expect(document.paths['/api/v1/backtests/{id}/fills']?.get).toBeDefined();
    expect(
      document.paths['/api/v1/backtests/{id}/methodology']?.get,
    ).toBeDefined();
    expect(document.paths['/api/v1/experiments']?.get).toBeDefined();
    expect(document.paths['/api/v1/experiments']?.post).toBeDefined();
    expect(document.paths['/api/v1/experiments/{id}']?.get).toBeDefined();
    expect(
      document.paths['/api/v1/experiments/{id}/cancel']?.post,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/experiments/{id}/results']?.get,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/experiments/{id}/matrix']?.get,
    ).toBeDefined();
    expect(
      document.paths['/api/v1/experiments/{id}/export']?.post,
    ).toBeDefined();
    expect(
      JSON.stringify(document.paths['/api/v1/backtests']?.post?.parameters),
    ).toContain('Idempotency-Key');
    expect(
      JSON.stringify(
        document.paths['/api/v1/backtests/{id}/trades']?.get?.parameters,
      ),
    ).toContain('cursor');
    const chartParameters =
      document.paths['/api/v1/symbols/{symbol}/chart']?.get?.parameters;
    for (const parameter of [
      'timeframe',
      'from',
      'to',
      'limit',
      'adjustmentMode',
      'overlays',
      'includePatterns',
      'includeCorporateActions',
      'includeUserMarkers',
    ])
      expect(JSON.stringify(chartParameters)).toContain(parameter);
    expect(
      JSON.stringify(document.paths['/api/v1/alerts']?.get?.parameters),
    ).toContain('cursor');
    expect(
      JSON.stringify(document.paths['/api/v1/notifications']?.get?.parameters),
    ).toContain('unread');
    expect(
      JSON.stringify(document.components?.schemas?.UpdateAlertDto),
    ).toContain('expectedRevision');
    expect(
      JSON.stringify(
        document.components?.schemas?.UpdateNotificationPreferencesDto,
      ),
    ).toContain('timezone');
    const listParameters =
      document.paths['/api/v1/indicators']?.get?.parameters;
    expect(JSON.stringify(listParameters)).toContain('category');
    expect(JSON.stringify(listParameters)).toContain('search');
    expect(JSON.stringify(listParameters)).toContain('status');
    const createParameters =
      document.paths['/api/v1/scanner/runs']?.post?.parameters;
    expect(JSON.stringify(createParameters)).toContain('Idempotency-Key');
    expect(
      document.paths['/api/v1/scanner/runs']?.post?.responses,
    ).toHaveProperty('200');
    expect(
      document.paths['/api/v1/scanner/runs']?.post?.responses,
    ).toHaveProperty('201');
    const resultParameters =
      document.paths['/api/v1/scanner/runs/{runId}/results']?.get?.parameters;
    expect(JSON.stringify(resultParameters)).toContain('cursor');
    expect(JSON.stringify(resultParameters)).toContain('includeExplanation');
    const watchlistParameters =
      document.paths['/api/v1/watchlists']?.get?.parameters;
    expect(JSON.stringify(watchlistParameters)).toContain('cursor');
    expect(JSON.stringify(watchlistParameters)).toContain('includeDeleted');
    const summaryParameters =
      document.paths['/api/v1/watchlists/{id}/market-summary']?.get?.parameters;
    expect(JSON.stringify(summaryParameters)).toContain('cursor');
    expect(JSON.stringify(summaryParameters)).toContain('limit');
    expect(document.components?.securitySchemes).toHaveProperty('bearer');
    const progressSchema = document.components?.schemas?.ScanRunProgressDto;
    expect(JSON.stringify(progressSchema)).toContain('source');
    expect(JSON.stringify(progressSchema)).toContain('stale');
    expect(JSON.stringify(progressSchema)).toContain('terminal');
    expect(JSON.stringify(progressSchema)).toContain('pollAfterMs');
  });
});
