CREATE TABLE "user_preferences" (
  "user_id" uuid PRIMARY KEY NOT NULL,
  "locale" varchar(16) DEFAULT 'tr-TR' NOT NULL,
  "timezone" varchar(64) DEFAULT 'Europe/Istanbul' NOT NULL,
  "date_format" varchar(24) DEFAULT 'dd.MM.yyyy' NOT NULL,
  "number_format" varchar(16) DEFAULT 'tr-TR' NOT NULL,
  "currency" varchar(3) DEFAULT 'TRY' NOT NULL,
  "default_market" varchar(24) DEFAULT 'BIST' NOT NULL,
  "default_benchmark" varchar(32) DEFAULT 'XU100' NOT NULL,
  "default_chart_adjustment" varchar(24) DEFAULT 'adjusted' NOT NULL,
  "default_timeframe" varchar(16) DEFAULT '1d' NOT NULL,
  "notification_channels" jsonb DEFAULT '["in_app","email"]'::jsonb NOT NULL,
  "quiet_hours" jsonb DEFAULT '{"enabled":false,"startMinute":null,"endMinute":null}'::jsonb NOT NULL,
  "accessibility" jsonb DEFAULT '{"reducedMotion":false}'::jsonb NOT NULL,
  "display" jsonb DEFAULT '{"compactTable":false,"methodologyDetailLevel":"standard"}'::jsonb NOT NULL,
  "onboarding_state" jsonb DEFAULT '{"status":"not_started","currentStep":"disclosure","completedSteps":[],"demoDataRequested":false,"completedAt":null}'::jsonb NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "user_preferences_user_id_security_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."security_users"("id") ON DELETE cascade,
  CONSTRAINT "user_preferences_version_check" CHECK ("version" > 0),
  CONSTRAINT "user_preferences_json_size_check" CHECK (octet_length("quiet_hours"::text) <= 1024 and octet_length("accessibility"::text) <= 1024 and octet_length("display"::text) <= 2048 and octet_length("onboarding_state"::text) <= 8192),
  CONSTRAINT "user_preferences_currency_check" CHECK ("currency" ~ '^[A-Z]{3}$')
);
