export type PortfolioErrorCode =
  | 'PORTFOLIO_NOT_FOUND'
  | 'PORTFOLIO_ACCESS_DENIED'
  | 'PORTFOLIO_DELETED'
  | 'PORTFOLIO_CONFLICT'
  | 'PORTFOLIO_INVALID'
  | 'PORTFOLIO_TRANSACTION_NOT_FOUND'
  | 'PORTFOLIO_TRANSACTION_ACCESS_DENIED'
  | 'PORTFOLIO_TRANSACTION_IMMUTABLE'
  | 'PORTFOLIO_TRANSACTION_INVALID_STATE'
  | 'PORTFOLIO_TRANSACTION_INVALID'
  | 'PORTFOLIO_TRANSACTION_TYPE_UNSUPPORTED'
  | 'PORTFOLIO_INSUFFICIENT_POSITION'
  | 'PORTFOLIO_IDEMPOTENCY_KEY_REQUIRED'
  | 'PORTFOLIO_IDEMPOTENCY_CONFLICT'
  | 'PORTFOLIO_ALREADY_REVERSED'
  | 'PORTFOLIO_DECIMAL_INVALID'
  | 'PORTFOLIO_DECIMAL_OVERFLOW'
  | 'PORTFOLIO_CORPORATE_ACTION_DUPLICATE'
  | 'PORTFOLIO_VALUATION_INVALID'
  | 'PORTFOLIO_PERFORMANCE_NOT_EVALUABLE'
  | 'PORTFOLIO_RECALCULATE_RATE_LIMITED'
  | 'PORTFOLIO_CSV_INVALID'
  | 'PORTFOLIO_IMPORT_NOT_FOUND'
  | 'PORTFOLIO_IMPORT_ACCESS_DENIED'
  | 'PORTFOLIO_IMPORT_INVALID_STATE'
  | 'PORTFOLIO_IMPORT_EXPIRED'
  | 'PORTFOLIO_IMPORT_ATOMIC_VALIDATION_FAILED';

export class PortfolioError extends Error {
  override readonly name = 'PortfolioError';

  constructor(
    readonly code: PortfolioErrorCode,
    readonly details?: unknown,
  ) {
    super(code);
  }
}
